FROM node:14-alpine
WORKDIR /app
COPY ./ .

RUN ls -a
RUN npm install
RUN npm run build

## this is stage two , where the app actually runs
FROM node:14-alpine
WORKDIR /app
COPY package.json ./

RUN npm install --only=production

COPY --from=0 /app/dist .

EXPOSE 3015
CMD ["node","index.js"]